### PR TITLE
add support to use payment method token aside from nonce

### PR DESCRIPTION
**Pull request by bryglen**

### CODE REVIEW

**Comment by bryglen** [comment]
Reference: https://developers.braintreepayments.com/ios+php/guides/transactions#sale

**Comment by bryglen** [comment]
@barryvdh can you accept this PR?

**Comment by barryvdh** [comment]
Can you add some tests?

**Comment by bryglen** [comment]
added unit testing.

**Comment by bryglen** [comment]
any updates on the PR? @barryvdh

**Comment by barryvdh** [comment]
Wouldn't it make more sense to use getNonce() or something? Not really sure what is the best way here.
Now we're doing getToken() to get the nonce?

**Comment by bryglen** [comment]
that's my first thinking as well but that would make some BC so I am worried to other people who already done it.

**Comment by barryvdh** [comment]
Why would they have done it already?

**Comment by bryglen** [comment]
they will have breaking changes because the current `token` is using `paymentTokenNonce` 

new implementation will be like this
```php
$gateway->purchase([
   'nonce' => $_POST['payment_method_none']
]);
```

old implementation is like this
```php
$gateway->purchase([
   'token' => $_POST['payment_method_none']
])
```

**Comment by barryvdh** [comment]
I think we used `token` because that's the default field, for that purpose.
Perhaps a `setPaymentMethodToken()` field instead, and if that is set, use that instead of the token?
@kayladnls what do you  think?

**Comment by bryglen** [comment]
and how about `$this->validate('amount', 'token')`?  basically one of them must be set at least, and if we put `if and else` it looks like something odd because it will be like this

```php
if ($this->getPaymentMethodToken()) {
   $this->validate('amount', 'paymentToken');
} else {
  $this->validate('amount', 'paymentNonce');
}
```

**Comment by barryvdh** [comment]
Or just leave it out of the validate, and check it manully:

f ($this->getPaymentMethodToken()) {
    $data['paymentMethodToken'] = $this->getPaymentMethodToken();
} elseif($this->getToken()) {
    $data['paymentMethodNonce'] = $this->getToken();
} else {
    throw new InvalidRequestException("The token (payment nonce) or paymentMethodToken field should be set.");
}

**Comment by bryglen** [comment]
that can do.. 1 concern to me is the `getToken()` vs `getPaymentMethodToken()` can be confusing to some developers, unless we do `getPaymentMethodNonce()` vs `getPaymentMethodToken()` but we will have a breaking changes. 

so my least suggestion is to use my PR `usePaymentMethodToken` or use this `getPaymentMethodNonce()` vs `getPaymentMethodToken()` which cause BC

**Comment by barryvdh** [comment]
I'd rather use `token` because that's a 'standard' field, but perhaps we could make it an alias (eg. `setPaymentNonce()` could set the token field.

**Comment by bryglen** [comment]
ok good idea! let me know what would be the final and i'll adjust my PR accordingly

**Comment by barryvdh** [comment]
Okay, what I said last, would be fine I guess :)

**Comment by bryglen** [comment]
updated the PR

**Comment by barryvdh** [comment]
THanks!

**Pull request merged**
