### PR TITLE
Updates to use current 5.x Braintree SDK and PHP 7.2

### PR DESCRIPTION
**Pull request by kbussche**
Removes prior support for older versions of php to allow the use of the current braintree PHP SDK.

### CODE REVIEW

**Comment by barryvdh** [comment]
The current 3.x branch is still supported until 2023. The problem was with the class_alias usage, right? Can't we just use the real namespace for 3.x?

**Comment by kbussche** [comment]
> The current 3.x branch is still supported until 2023. The problem was with the class_alias usage, right? Can't we just use the real namespace for 3.x?

I can circle back and try to make a new PR that fixes the name spacing with the 3.x SDK.  But would you be opposed to making a 4.0 tag on omnipay-braintree so that there is an option to use the newer 5.0 SDK?

**Comment by barryvdh** [comment]
Let's just do this for now, guess people can just use it like before on old php versions.

**Comment by kbussche** [comment]
Does the 4.0 tag need to be created on packagist?

**Comment by barryvdh** [comment]
I updated the branch alias, so you can test the `@dev` version.

**Pull request merged**
