### PR TITLE
add Customer, PaymentMethod, MerchantAccount support

### PR DESCRIPTION
**Pull request by iampersistent**
Added Create, Delete and Update Customer. Allow CustomerId to be passed into ClientToken.

### CODE REVIEW

**Comment by iampersistent** [comment]
I just realized that the options I added in ClientTokenRequest doesn't match the way options are currently being handled. I'm making a fix now.

**Comment by iampersistent** [comment]
Updated.

**Comment by iampersistent** [comment]
@barryvdh @kayladnls ping

**Comment by iampersistent** [comment]
There will be some conflicts between this and #3 . If you'll merge @bryglen first, I'll update my code to match.

**Comment by barryvdh** [comment]
#3 is merged!

**Comment by iampersistent** [comment]
@barryvdh rebased and ready to go

**Comment by barryvdh** [comment]
Thanks!

**Pull request merged**
