### PR TITLE
Subscriptions/Webhooks

### PR DESCRIPTION
**Pull request by c0nstantx**
This PR adds functionality for create/cancel Braintree subscriptions and parse webhook notifications

### CODE REVIEW

**Comment by c0nstantx** [comment]
Braintree [SDK](https://developers.braintreepayments.com/start/hello-server/php) requires PHP 5.4.0 or higher. Maybe unit testing in PHP 5.3 should be removed ?

**Comment by barryvdh** [comment]
This library currently supports SDK `^2.39|^3.0`. V2 has 5.3 support.
Also, notification support was added in v2.14, so should be available in 5.3, right?

**Comment by c0nstantx** [comment]
That's true, but you have to either remove [v3](https://github.com/braintree/braintree_php/blob/master/CHANGELOG.md#300) from the library, since it needs at least PHP 5.4 or you have to remove PHP 5.3 unit testing environment.
The issue appeared when Travis run 5.3 tests for Webhooks with the current composer requirements.

**Comment by barryvdh** [comment]
But when Travis installs the dependancies, it should install v2 right, because v3 isn't supported.

**Comment by c0nstantx** [comment]
I checked Travis [log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/97196053/log.txt) and it does actually installs [2.40.1](https://github.com/braintree/braintree_php/tree/5d4d2a4aab8690d0e7dbca3f168c9b6575f856de).

But for some reason, PHP 5.3 unit test for WebHooks fail.
I 'll give it a look again

**Comment by c0nstantx** [comment]
I figured it out. It seems, that in my environment, composer was installing Braintree SDK 3.x, which has different WebhookNotification implementation. I saw the same error Travis thrown when I removed 3.x version from my local composer.json and I run composer update.
I updated the unit test for both major versions, but IMHO, this option of 2.x or 3.x SDKs along with PHP 5.3 compatibility might be a drawback :)

**Pull request merged**
