### PR TITLE
AVS Rules Updates

### PR DESCRIPTION
**Pull request by ivanmitrikeski**

### CODE REVIEW

**Comment by ivanmitrikeski** [comment]
Braintree AVS rules require address to be sent to Braintree when set in Braintree Processing Options.

**Comment by barryvdh** [comment]
Can you fix the build?

**Comment by barrycarrjr** [comment]
> 
> 
> Can you fix the build?

@barryvdh we fixed this a few years ago and have been using the changes with no issues. Can you merge this into master?

**Comment by barryvdh** [comment]
Bit the tests are still failing? The 5.3 don't matter

**Comment by barryvdh** [comment]
Okay I'll run the tests again.

**Comment by barrycarrjr** [comment]
> 
> 
> Bit the tests are still failing? The 5.3 don't matter

@barryvdh i fixed the tests. Build [#96 now passes](https://travis-ci.org/github/thephpleague/omnipay-braintree/builds/760395040)

**Comment by barryvdh** [comment]
Thanks!

**Comment by jason-nabooki** [comment]
@barryvdh @barrycarrjr @ivanmitrikeski  This may need to be rolled back. An address isn't required for braintree but now with this update it's rejecting any transaction where there's no address specified.

message=Addresses must have at least one field filled in

I rolled back to the previous commit and I can now make transactions again.

**Comment by barrycarrjr** [comment]
@jason-nabooki good catch. Ivan and myself will look into this at some point today and create a new PR

**Comment by jason-nabooki** [comment]
Thanks @barrycarrjr. To replicate the issue I created a brand new Braintree sandbox with no AVS rules configured.

If you'd like me to create an issue for this let me know. I should have probably done that first, sorry.

**Comment by barrycarrjr** [comment]
> Thanks @barrycarrjr. To replicate the issue I created a brand new Braintree sandbox with no AVS rules configured.

excellent. will add to our notes

> If you'd like me to create an issue for this let me know. I should have probably done that first, sorry.

we do not require an issue as we use jira internally but if you want to create an issue it might not hurt so no one else reports the same problem. if you do end up creating an issue just mention me so i can add notes to it once its resolved.

**Pull request merged**
